parameters:

services:
    acilia.metatags:
        class: Acilia\Bundle\MetaTagsBundle\Service\MetaTagsService
        arguments: [@kernel]

    acilia.metatags.twig_extension:
        class: Acilia\Bundle\MetaTagsBundle\Library\Twig\Extension\MetaTagsExtension
        arguments: [@core.metatags]
        tags:
          - { name: twig.extension }
